from pathlib import Path

latex = r"""
\section{Bermudan Portfolio XVA under a Frozen Clean Exercise Policy}
\label{sec:bermudan_xva_frozen_policy}

We now describe a Bermudan-option extension of the DeepXVA setup in which the clean exercise policy is assumed to be known in advance through a trained continuation-value network. The purpose of this section is to make precise how the general dividend-stream formulation of the clean price leads to an XVA BSDE for a Bermudan portfolio, and to document a portfolio construction and simulation protocol in sufficient detail that the implementation can be reproduced directly from the description.

The conceptual starting point is that the European specialization used in the basic DeepXVA exposition is not essential for the XVA layer itself. What matters for the reduction to the XVA BSDE is the existence of a clean portfolio value process \(\hat V_t\) under the market filtration \((\mathcal F_t)\). For Bermudan options, \(\hat V_t\) is not given by a single terminal payoff at maturity, but by an \(\mathcal F\)-adapted dividend stream generated by the exercise policy. Thus the right entry point is the general clean-value representation in equations (2.4)--(2.5) of the paper rather than the European specialization in equation (2.6).

Consider a portfolio of \(M\) Bermudan put options written on a \(d\)-dimensional Markov risk-factor process \(X_t \in \mathbb R^d\) defined on a filtered probability space
\[
(\Omega,\mathcal F,(\mathcal F_t)_{t\in[0,T]},Q).
\]
The factor process is simulated under the risk-neutral measure \(Q\). For the purpose of a prototype, it is enough to assume that \(X\) is a diffusion with sufficiently regular dynamics for path simulation. In the code prototype we used a correlated lognormal model,
\[
dX_t^k = \sigma_k X_t^k\, dW_t^{k,Q}, \qquad k=1,\dots,d,
\]
with constant volatilities \(\sigma_k>0\) and correlated Brownian motion satisfying
\[
d\langle W^{i,Q},W^{j,Q}\rangle_t = \rho_{ij}\,dt,
\]
where \(\rho\in\mathbb R^{d\times d}\) is positive definite. This choice is not mathematically essential; any simulator that returns pathwise states \(X_{t_n}\) and Brownian increments \(\Delta W_n\) on a Bermudan grid can be plugged into the construction below.

Let the Bermudan exercise grid be
\[
0=t_0<t_1<\cdots<t_N=T.
\]
Each option \(m\in\{1,\dots,M\}\) is specified by the tuple
\[
\bigl(a_m, K_m, N_m, s_m, \mathcal E_m\bigr),
\]
where \(a_m\in\{1,\dots,d\}\) is the underlying asset index, \(K_m>0\) is the strike, \(N_m>0\) is the notional, \(s_m\in\{+1,-1\}\) is the position sign (\(+1\) for a long Bermudan put and \(-1\) for a short Bermudan put), and \(\mathcal E_m\subseteq\{0,\dots,N\}\) is the set of exercise dates available to that option. In the prototype implementation each Bermudan put has payoff
\[
g_m(X_{t_n}) = s_m N_m \bigl(K_m - X_{t_n}^{a_m}\bigr)^+,
\qquad n\in\mathcal E_m.
\]
Although the portfolio may be large, every option is driven by the same global factor process \(X\), so the state dimension remains \(d\) while the portfolio size is \(M\).

\paragraph{Clean price from the dividend-stream formulation.}
For each option \(m\), let \(A^m\) denote its cumulative clean dividend process. The clean value is then, exactly as in the general formulation of the paper,
\begin{equation}
\hat V_t^m
=
B_t^r\,\mathbb E^Q\!\left[
\int_{(t,T]} \frac{dA_u^m}{B_u^r}
\;\middle|\;
\mathcal F_t
\right],
\label{eq:berm_clean_dividend}
\end{equation}
where \(B_t^r=\exp(\int_0^t r_s\,ds)\) is the money-market account associated with the reference discount rate \(r_t\). For a Bermudan claim, the process \(A^m\) is generated by an optimal stopping rule. In our setup, however, the stopping rule is not recomputed jointly with XVA. Instead, it is frozen from the clean problem.

Specifically, assume a single trained continuation-value network
\[
c_\theta(n,x;\varphi_m),
\]
is available for all options in the portfolio. Here \(n\) is the time index, \(x\in\mathbb R^d\) is the current factor state, and \(\varphi_m\) is a vector of static option features describing option \(m\). In the code, the option feature vector may include, for example,
\[
\varphi_m =
\bigl(a_m,\; K_m,\; N_m,\; s_m,\; \min \mathcal E_m,\; \max \mathcal E_m,\; t_{\min\mathcal E_m},\; t_{\max\mathcal E_m}\bigr).
\]
The interpretation is that the network returns an approximation of the clean continuation value of option \(m\) at exercise date \(t_n\), conditional on the current state \(X_{t_n}=x\).

The frozen clean exercise rule is then
\begin{equation}
\tau_m^\star
=
\inf\Bigl\{
t_n \in \{t_0,\dots,t_N\} \cap \mathcal E_m
:
g_m(X_{t_n}) \ge c_\theta(n,X_{t_n};\varphi_m)
\Bigr\}.
\label{eq:frozen_clean_stopping_time}
\end{equation}
Equivalently, the option is exercised at the first exercise date where immediate exercise dominates the learned clean continuation value. Once exercised, the option disappears from the portfolio. The cumulative dividend process can therefore be written as
\[
A_t^m = g_m(X_{\tau_m^\star})\,\mathbf 1_{\{t\ge \tau_m^\star\}},
\]
and the clean value process becomes
\begin{equation}
\hat V_t^m
=
\mathbb E^Q\!\left[
\frac{B_t^r}{B_{\tau_m^\star}^r}
g_m(X_{\tau_m^\star})
\;\middle|\;
\mathcal F_t
\right].
\label{eq:berm_clean_value_stopped}
\end{equation}
The total clean portfolio value is the sum
\begin{equation}
\hat V_t = \sum_{m=1}^M \hat V_t^m.
\label{eq:berm_portfolio_clean_value}
\end{equation}

\paragraph{Discrete Bermudan-grid valuation used in the implementation.}
The implementation works directly on the Bermudan grid. Suppose \(K\) Monte Carlo paths of the factor process are simulated:
\[
\{X_{t_n}^{(i)} : i=1,\dots,K,\; n=0,\dots,N\}.
\]
For each option \(m\) and each path \(i\), define an alive indicator \(L_{n}^{(i,m)}\in\{0,1\}\), where \(L_n^{(i,m)}=1\) means option \(m\) is still alive immediately before the exercise decision at time \(t_n\). Initially,
\[
L_0^{(i,m)} = 1 \qquad \text{for all } i,m.
\]
At time \(t_n\), compute the immediate exercise payoff
\[
g_n^{(i,m)} := g_m(X_{t_n}^{(i)})
\]
and the network continuation estimate
\[
c_n^{(i,m)} := c_\theta(n, X_{t_n}^{(i)}; \varphi_m).
\]
If \(t_n\notin \mathcal E_m\), no exercise decision is made. If \(t_n\in \mathcal E_m\), the clean-policy exercise indicator is
\begin{equation}
E_n^{(i,m)}
=
L_n^{(i,m)}\,
\mathbf 1_{\{t_n\in\mathcal E_m\}}\,
\mathbf 1_{\{g_n^{(i,m)} \ge c_n^{(i,m)}\}}.
\label{eq:exercise_indicator}
\end{equation}
The pathwise exercise cash flow is then
\begin{equation}
CF_n^{(i,m)} = E_n^{(i,m)}\, g_n^{(i,m)}.
\label{eq:exercise_cashflow}
\end{equation}
After the decision at \(t_n\), the alive status is updated by
\begin{equation}
L_{n+1}^{(i,m)} = L_n^{(i,m)}\bigl(1-E_n^{(i,m)}\bigr).
\label{eq:alive_update}
\end{equation}
In words, an exercised option is removed permanently from all future dates.

The code stores, for every path and option, a pathwise clean-value approximation \(V_n^{(i,m)}\) on the Bermudan grid. At exercise dates, if the option is alive, the clean value is approximated by
\begin{equation}
V_n^{(i,m)}
=
L_n^{(i,m)} \max\bigl(g_n^{(i,m)}, c_n^{(i,m)}\bigr),
\qquad t_n\in\mathcal E_m.
\label{eq:pathwise_clean_value_exercise_dates}
\end{equation}
At non-exercise dates, the implementation uses one-step discounting of the next-grid value:
\begin{equation}
V_n^{(i,m)}
=
L_n^{(i,m)}\, P(t_n,t_{n+1})\, V_{n+1}^{(i,m)},
\qquad t_n\notin\mathcal E_m,
\label{eq:pathwise_clean_value_nonexercise_dates}
\end{equation}
where \(P(t_n,t_{n+1}) = B_{t_n}^r/B_{t_{n+1}}^r\) is the deterministic discount factor from the reference curve. This produces a pathwise approximation of the clean Bermudan value process under the frozen policy. The aggregate clean portfolio value on path \(i\) is then
\begin{equation}
\hat V_n^{(i)} = \sum_{m=1}^M V_n^{(i,m)}.
\label{eq:aggregate_clean_value_paths}
\end{equation}

This approximation is consistent with the implementation assumption that the continuation network is already trained and can be used as a plug-in clean continuation oracle. It is not a proof-level representation of the exact Snell envelope, but it is the natural object to feed into the XVA layer for a prototype.

\paragraph{Collateral, credit, and funding models.}
To isolate the nonlinear funding recursion while retaining counterparty risk, we keep CVA and FVA and drop DVA and ColVA. Counterparty default is modeled by a deterministic intensity \(\lambda_t^C\) under \(Q\) and recovery rate \(R_C\in[0,1]\). The own-default intensity is set to zero, and collateral remuneration is assumed to coincide with the reference rate \(r_t\), so there is no DVA or ColVA contribution.

Collateral is generated from the clean portfolio value using a threshold CSA. Let \(H\ge 0\) be the collateral threshold. Then for each path and time step,
\begin{equation}
C_n^{(i)}
=
\begin{cases}
\hat V_n^{(i)} - H, & \hat V_n^{(i)} > H,\\[4pt]
0, & |\hat V_n^{(i)}|\le H,\\[4pt]
\hat V_n^{(i)} + H, & \hat V_n^{(i)} < -H.
\end{cases}
\label{eq:berm_csa_threshold}
\end{equation}
This is exactly the collateral rule implemented in the code. The unsecured exposure relevant for CVA is \(\hat V_n^{(i)} - C_n^{(i)}\).

Funding rates are modeled as deterministic spreads over the reference rate:
\[
r_t^{f,b} = r_t + s_t^{b},
\qquad
r_t^{f,l} = r_t + s_t^{l},
\]
where \(s_t^b\) and \(s_t^l\) are the borrowing and lending spreads. Typically \(s_t^b>0\) and \(s_t^l\ge 0\), with \(s_t^b\) larger than \(s_t^l\). The net funding requirement is
\begin{equation}
F_t = \hat V_t - XVA_t - C_t.
\label{eq:berm_funding_need}
\end{equation}
Positive \(F_t\) corresponds to a borrowing need, while negative \(F_t\) corresponds to excess cash that can be invested. This sign dependence is the source of the nonlinearity in the XVA BSDE.

\paragraph{XVA BSDE for the Bermudan portfolio.}
Under the frozen clean exercise policy, the XVA layer has exactly the same mathematical structure as in the European case. The only difference is that the clean value process \(\hat V_t\) now comes from the stopped Bermudan portfolio rather than from a terminal European payoff. On intervals between exercise dates, the reduced-filtration XVA process solves
\begin{equation}
-dXVA_t
=
\bar f(t,\hat V_t,XVA_t)\,dt
-
Z_t\, dW_t^Q,
\qquad
XVA_T=0,
\label{eq:berm_xva_bsde_continuous}
\end{equation}
with driver
\begin{align}
\bar f(t,\hat V_t,XVA_t)
&=
-(1-R_C)(\hat V_t-C_t)^- \lambda_t^C
+(r_t^{f,l}-r_t)(\hat V_t-XVA_t-C_t)^+
-(r_t^{f,b}-r_t)(\hat V_t-XVA_t-C_t)^-
\nonumber\\
&\qquad
-(r_t+\lambda_t^C)XVA_t.
\label{eq:berm_xva_driver}
\end{align}
This is the CVA+FVA specialization of the DeepXVA reduced BSDE. The first term is the CVA loss rate due to counterparty default on negative unsecured exposure. The second and third terms are the lending and borrowing contributions to FVA. The final term is the discounting/killing term after reduction from the enlarged filtration.

In the discrete Bermudan-grid implementation provided to the BSDE solver, the problem is represented on times \(t_0,\dots,t_N\). Given the simulated paths and the precomputed clean Bermudan portfolio values \(\hat V_n^{(i)}\), the driver seen by the solver at step \(n\) is
\begin{align}
\bar f_n^{(i)}(y)
&=
-(1-R_C)\bigl(\hat V_n^{(i)}-C_n^{(i)}\bigr)^- \lambda_{t_n}^C
+\bigl(r_{t_n}^{f,l}-r_{t_n}\bigr)\bigl(\hat V_n^{(i)}-y-C_n^{(i)}\bigr)^+
\nonumber\\
&\qquad
-\bigl(r_{t_n}^{f,b}-r_{t_n}\bigr)\bigl(\hat V_n^{(i)}-y-C_n^{(i)}\bigr)^-
-\bigl(r_{t_n}+\lambda_{t_n}^C\bigr)y.
\label{eq:berm_xva_driver_discrete}
\end{align}
The BSDE solver receives the tuple
\[
\bigl(t_n,\; X_{t_n}^{(i)},\; \Delta W_n^{(i)},\; \hat V_n^{(i)},\; C_n^{(i)}\bigr)
\]
for all paths \(i\) and times \(n\), together with the terminal condition \(XVA_T=0\). This is exactly how the \texttt{XVAProblem} object is organized in code.

\paragraph{How exercise dates interact with the XVA recursion.}
Because the portfolio composition changes when options are exercised, the clean value process \(\hat V_t\) is naturally c\`adl\`ag with deterministic intervention dates at the Bermudan exercise times. In the implementation, this is handled implicitly by constructing \(\hat V_n^{(i)}\) on the grid after applying the exercise rule pathwise. Once an option exercises on a given path, its future clean values and future contributions to the collateral base are set to zero on that path. Consequently, the BSDE solver does not need to model a separate jump term for exercise; it only sees the already-updated clean portfolio value and collateral arrays on the grid.

\paragraph{Portfolio construction used in the example code.}
The example code constructs a reproducible portfolio as follows. A Bermudan grid over three years is created with quarterly dates:
\[
t_n = \frac{n}{4}, \qquad n=0,1,\dots,12.
\]
Thus \(N=12\). The factor dimension is taken to be \(d=20\), and the initial state vector is
\[
x_0 = (90,\,91.0526,\,\dots,\,110),
\]
namely 20 equally spaced values between 90 and 110. Constant volatilities \(\sigma_k=20\%\) are used for all factors, and the correlation matrix is
\[
\rho_{ij} =
\begin{cases}
1, & i=j,\\
0.3, & i\ne j,
\end{cases}
\]
which in matrix form is \(0.3\,\mathbf 1\mathbf 1^\top + 0.7 I\).

The sample portfolio uses the first eight underlying assets, so \(a_m\in\{1,\dots,8\}\). For each of these eight assets, 15 Bermudan puts are created, leading to a total portfolio size
\[
M = 8\times 15 = 120.
\]
All options share the same exercise dates
\[
\mathcal E_m = \{3,6,9,12\},
\]
which correspond to times \(0.75\), \(1.5\), \(2.25\), and \(3.0\) years on the quarterly grid. For each option, the strike is chosen as one of three moneyness levels relative to the initial spot of its underlying:
\[
K_m \in \{0.9 S_0^{a_m},\; S_0^{a_m},\; 1.1 S_0^{a_m}\}.
\]
The notional is drawn from the set
\[
N_m \in \{5\times 10^5,\; 10^6,\; 2\times 10^6\},
\]
and the sign is chosen as \(s_m\in\{+1,-1\}\), allowing both long and short Bermudan puts. The random selections are controlled by a fixed random seed so that the construction is reproducible.

The discount curve in the example is flat:
\[
P(0,t)=e^{-0.03 t},
\]
so the reference short rate is \(r_t=3\%\). The counterparty intensity is flat at
\[
\lambda_t^C = 1.5\%,
\]
with recovery \(R_C=40\%\). The collateral threshold is set to
\[
H = 2\times 10^6.
\]
The funding borrowing spread is set to \(100\) basis points and the lending spread to \(0\), namely
\[
r_t^{f,b}=r_t+0.01,
\qquad
r_t^{f,l}=r_t.
\]
The code then simulates \(20{,}000\) Monte Carlo paths of the factor process, applies the shared continuation network to produce pathwise stopping decisions and clean values, aggregates these into the clean portfolio value process \(\hat V\), computes collateral \(C\), and finally exposes an \texttt{XVAProblem} object with the data arrays
\[
t,\; X,\; \Delta W,\; \hat V,\; C,\; \text{exercise},\; \text{cashflow},\; \text{option\_value},\; \text{alive},
\]
together with a callable driver implementing \eqref{eq:berm_xva_driver_discrete}.

\paragraph{Interpretation and scope.}
This construction is intentionally a first-step Bermudan extension of DeepXVA rather than a full exercise-under-XVA model. The exercise rule is frozen from the clean problem, so the continuation network is used only to determine the clean stopping policy and the clean value approximation. Once that is done, the XVA layer is solved conditionally on the resulting clean portfolio process. The advantage of this choice is that it preserves the standard DeepXVA BSDE structure while allowing the portfolio to contain early-exercise features and pathwise exercise-driven portfolio attrition.

If one wished to move beyond this approximation, the exercise decision itself would have to depend on the full adjusted value \(V_t=\hat V_t-XVA_t\), and the problem would become a nonlinear optimal stopping problem, more naturally expressed as a reflected BSDE or obstacle problem. That is a much harder class of problems and is not what the current code implements. The present section should therefore be read as documentation for the frozen-clean-policy Bermudan prototype.
"""

path = Path("/mnt/data/bermudan_xva_section.tex")
path.write_text(latex)
print(f"Wrote {path}")
